// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2SkYRLc1_B0j48C5CVpwZHlHsWcbbuU',
    appId: '1:270237113838:web:be34ae0c260673e125c2ff',
    messagingSenderId: '270237113838',
    projectId: 'reddit-clone-9ef04',
    authDomain: 'reddit-clone-9ef04.firebaseapp.com',
    storageBucket: 'reddit-clone-9ef04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBVOKcz5ypRkfqGUycPbi15L_0NJJCpE',
    appId: '1:270237113838:android:b51ab29fa1ec657e25c2ff',
    messagingSenderId: '270237113838',
    projectId: 'reddit-clone-9ef04',
    storageBucket: 'reddit-clone-9ef04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0LQCZvd7ETMzsQmn8vSfqMN_x7moklE',
    appId: '1:270237113838:ios:257445a663d2a7e725c2ff',
    messagingSenderId: '270237113838',
    projectId: 'reddit-clone-9ef04',
    storageBucket: 'reddit-clone-9ef04.appspot.com',
    iosClientId: '270237113838-preok32fhlm2kcf6241idtthf590gat5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0LQCZvd7ETMzsQmn8vSfqMN_x7moklE',
    appId: '1:270237113838:ios:257445a663d2a7e725c2ff',
    messagingSenderId: '270237113838',
    projectId: 'reddit-clone-9ef04',
    storageBucket: 'reddit-clone-9ef04.appspot.com',
    iosClientId: '270237113838-preok32fhlm2kcf6241idtthf590gat5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
  
}
